services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: pkm
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 80:80
    environment:
      PMA_HOST: db
volumes:
  db_data: